export default {
  //home页面
  banner:[],
  nowplay:[],
  coming:[],
  //detail页面
  detail:[],
  //film页面
  nowPlayingList:[],
  comingSoonList:[],
  nowPage:0,
  comingPage:0,
  getNowMore:true,
  getComingMore:true,
  //cinema页面
  cinemaList:[],
  district:[],
  isShowslide:false
};
